import faiss
import numpy as np
import pickle
from sentence_transformers import SentenceTransformer

# Modelo para embeddings
embedding_model = SentenceTransformer("Qwen/Qwen2.5-1.5B")

# Exemplo de documentos (pode carregar de um CSV, banco de dados, etc.)
documents = [
    " The patient, identified as PAT_1516, is 8 years old and has been evaluated for a lesion located on the arm. Specific details regarding the size of the lesion and the Fitzpatrick scale are not available. There is no available information about the family medical history, including the health of the parents or exposure to environmental factors such as piped water, sewage systems, and pesticide exposure. Regarding the patient's medical history, there are no records of skin cancer history or family cancer history. No data about lifestyle factors such as alcohol consumption or smoking are provided. Observed Symptoms: No symptoms such as itching, growth of the lesion, pain, changes in the lesion, bleeding, or elevation have been observed.",
    " The patient, identified as PAT_46, is a 55-year-old female with a concerning lesion on her neck measuring 6.0 x 5.0 mm, classified under Fitzpatrick skin type 3. With both a personal and family history of skin cancer, and parents hailing from Pomerania, her genetic predisposition necessitates careful monitoring. The lesion is symptomatic, exhibiting itching, growth, changes, bleeding, and elevation, yet notably, it is not painful. Environmental conditions are favorable, with access to clean water and no pesticide exposure, and her lifestyle is free of smoking and alcohol, which are beneficial for her overall health.",
    " The patient, identified as PAT_1545, is 77 years old and presents with a facial lesion. Specific details such as lesion size, Fitzpatrick skin type, gender, family medical history, and environmental or lifestyle factors are not available. The lesion currently shows only one symptom: itching. There are no signs of growth, pain, changes, bleeding, or elevation.Although the absence of additional symptoms may indicate a less aggressive lesion, the presence of itching, especially on the face in an elderly patient, warrants clinical attention. Further information and diagnostic evaluation are necessary to determine the lesion’s nature and rule out potential malignancy.",
    " The patient, identified as PAT_1989, is 75 years old and presents with a lesion located on the hand. Due to limited available information—such as lesion size, gender, Fitzpatrick skin type, family medical history, environmental exposure, and lifestyle habits—a comprehensive evaluation is currently not possible. The lesion presents with a single symptom: itching, while no signs of growth, pain, changes, bleeding, or elevation are reported.",
    " Patient ID PAT_684, a 79-year-old MALE with a lesion on the FOREARM measuring 5.0 x 5.0 mm, has a Fitzpatrick skin type of 1.0. He has a history of skin cancer and family medical history from his parents in POMERANIA. The patient does not have access to piped water or sewage systems and has no pesticide exposure. His lifestyle includes alcohol consumption but no smoking. Symptoms  include itching, growth, and bleeding, with no elevation changes noted.",
    " The patient, identified as PAT_1549, is 53 years old and presents with a lesion located on the chest. Specific information regarding the lesion’s size, gender, skin type, family background, environmental exposure, and lifestyle habits is currently unavailable. The lesion presents with itching and elevation, while no signs of growth, pain, changes, or bleeding have been reported. Although the limited clinical context hinders a complete evaluation, the presence of these symptoms—especially in a middle-aged patient—warrants further dermatological examination to rule out any underlying pathology.",
    " The patient, identified as PAT_778, is a 52-year-old female presenting with a lesion on the face measuring 15.0 x 10.0 mm. She has a Fitzpatrick skin type of 3. Her family background includes a German father and an Italian mother. She lives in a setting with access to piped water and a sewage system, and reports no exposure to pesticides. She has no personal history of skin cancer, but there is a family history of cancer. The patient does not smoke but does consume alcohol. The lesion is symptomatic, presenting with growth, changes in appearance, bleeding, and elevation, though there is no itching or pain reported. Given the lesion’s size, facial location, symptom profile, and family cancer history, prompt dermatological evaluation is strongly recommended to assess the risk of malignancy.",
    " The patient, identified as PAT_117, is a 74-year-old female presenting with a facial lesion measuring 15.0 x 10.0 mm. She has a Fitzpatrick skin type of 1, and both parents are from Pomerania. Her living conditions lack access to piped water and sewage systems, and she reports exposure to pesticides. She has no personal or family history of cancer. Her lifestyle is non-smoking and alcohol-free. The lesion is symptomatic, presenting with itching, growth, pain, bleeding, and elevation, though no visible changes in appearance have been noted. Given the lesion’s size, symptom profile, and facial location in an elderly patient with environmental exposure risks, further dermatological evaluation is highly recommended to determine the nature and urgency of treatment.",
    " The patient, identified as PAT_1995, is 68 years old and presents with a lesion located on the forearm. Specific information such as lesion size, gender, skin type, medical and family history, environmental exposure, and lifestyle factors is not available, limiting the completeness of the assessment. The lesion is currently exhibiting itching and visible changes in appearance, while no growth, pain, bleeding, or elevation have been reported. Despite the limited clinical context, the presence of itching and morphological changes in an elderly patient warrants further dermatological evaluation to determine potential risks and appropriate follow-up care.",
    " The patient, identified as PAT_705, is a 58-year-old female presenting with a lesion on the forearm measuring 9.0 x 7.0 mm. She has Fitzpatrick skin type 1 and a family background of German descent. Her environmental conditions include access to piped water and a sewage system, though she reports exposure to pesticides. Medically, the patient has a personal and family history of cancer. She does not smoke but consumes alcohol. The lesion is exhibiting growth but shows no other symptoms such as itching, pain, changes in appearance, bleeding, or elevation. Given the patient’s cancer history and the lesion’s growth behavior, further dermatological assessment is advised to rule out malignancy and determine the need for possible intervention.",
    " The patient, identified as PAT_2140, is 45 years old and presents with a lesion located on the neck. Information regarding lesion size, skin type, gender, family medical history, environmental exposures, and lifestyle factors is unavailable at this time. The lesion presents with itching and elevation, but no signs of growth, pain, changes in appearance, or bleeding have been reported. Although the symptom profile is limited, the presence of elevation and persistent itching suggests the need for further dermatological evaluation to assess potential risk and guide appropriate management.",
    " The patient, identified as PAT_967, is a 34-year-old female presenting with a lesion on the nose measuring 5.0 x 4.0 mm. She has a Fitzpatrick skin type of 2 and a family background from Pomerania. Her environmental conditions include lack of access to piped water and sewage systems, with reported pesticide exposure. Medically, she has a history of skin cancer, although no family history of cancer is reported. She does not smoke or consume alcohol. The lesion is currently associated with itching, bleeding, and elevation. Information regarding growth and visual changes is unknown. Given her age, cancer history, and the lesion’s symptoms and location on the face, further dermatological evaluation is strongly recommended to determine the need for biopsy or intervention.",
    " The patient, identified as PAT_2088, is a 9-year-old child presenting with a lesion on the chest. Details regarding the lesion’s size, skin type, gender, family medical history, environmental exposures, and lifestyle factors are currently unavailable. No symptoms have been reported — the lesion shows no signs of itching, growth, pain, changes in appearance, bleeding, or elevation. Given the absence of symptoms and the patient's young age, the lesion may be benign; however, continued monitoring is recommended to detect any future changes that may require medical attention.",
    " The patient, identified as PAT_636, is a 78-year-old female presenting with a large lesion on the chest, measuring 20.0 x 18.0 mm. She has a Fitzpatrick skin type of 2, and both parents are of Brazilian origin. Her living conditions include access to piped water and a sewage system, with no reported exposure to pesticides. She has a personal and family history of cancer, which increases clinical concern. The patient maintains a healthy lifestyle, with no smoking or alcohol use. The lesion is symptomatic, presenting with itching, growth, pain, changes in appearance, bleeding, and elevation—indicating an active and potentially high-risk profile. Given the size, location, symptom severity, and medical history, urgent dermatological evaluation and biopsy are strongly recommended to rule out malignancy and guide further treatment.",
    " The patient, identified as PAT_38, is a 52-year-old male presenting with a lesion on the thigh measuring 14.0 x 12.0 mm. He has Fitzpatrick skin type 1 and a family background of German descent. His environmental conditions include access to piped water but no sewage system, along with reported pesticide exposure. He has a personal and family history of skin cancer, which raises concern. The patient does not smoke or consume alcohol. The lesion currently presents with itching as the only symptom, with no reported growth, pain, changes, bleeding, or elevation. Given the lesion size, cancer history, and environmental risk factors, further dermatological evaluation is warranted to assess potential malignancy and determine appropriate clinical management.",
    " The patient, identified as PAT_741, is a 77-year-old male presenting with a lesion on the face measuring 13.0 x 13.0 mm. He has Fitzpatrick skin type 2 and a family background from Pomerania. Environmental conditions are stable, with access to piped water and sewage systems, and no reported pesticide exposure. Although he has no personal history of skin cancer, there is a family history of cancer. The patient is a smoker and does not consume alcohol. The lesion presents with itching and elevation; however, data on growth and changes are unknown, and no pain or bleeding has been reported. Given the lesion's facial location, size, symptom profile, smoking history, and family cancer background, a comprehensive dermatological evaluation is recommended to assess the potential for malignancy and determine appropriate management.",
    " The patient, identified as **PAT_380**, is a 60-year-old male with a small lesion on the nose, measuring 3.0 x 3.0 mm. He has Fitzpatrick skin type 2 and a mixed European family background, with paternal origin from the Netherlands and maternal from Germany. He lives in an environment with access to piped water and sewage systems, but reports exposure to pesticides. There is no personal history of skin cancer, although a family history of cancer is present. The patient maintains a healthy lifestyle with no smoking or alcohol consumption. The lesion presents with itching as the only symptom, with no signs of growth, pain, changes, bleeding, or elevation. While the lesion is small and minimally symptomatic, its location on the face and the patient’s family history of cancer suggest that further evaluation would be prudent to rule out any early signs of malignancy.",
    " The patient, identified as PAT_1783, is 75 years old and presents with a lesion located on the scalp. Information about lesion size, gender, skin type, family history, environmental factors, and lifestyle is not available, limiting the context of the evaluation. The lesion is currently asymptomatic except for elevation. There are no reports of itching, growth, pain, changes, or bleeding. While the lesion appears minimally symptomatic, its location on the scalp and the presence of elevation warrant clinical attention to determine its nature and rule out potential skin pathology, especially in an elderly patient."
    " The patient, identified as PAT_759, is a 74-year-old male presenting with a lesion on the nose measuring 5.0 x 3.0 mm. He has Fitzpatrick skin type 2, with both parents originating from Germany. He lives in an environment with access to piped water but without a sewage system, and he reports no pesticide exposure. He has no personal or family history of cancer and maintains a healthy lifestyle without smoking or alcohol consumption. The lesion exhibits multiple concerning symptoms, including itching, growth, bleeding, and elevation, though no pain or visible changes have been noted. Given the patient's age, lesion characteristics, and facial location, prompt dermatological evaluation is recommended to assess for possible malignancy and determine appropriate management.",
    " The patient, identified as PAT_821, is a 64-year-old female presenting with a lesion on the nose measuring 7.0 x 5.0 mm. She has Fitzpatrick skin type 2, and both parents originate from Pomerania. Her environment includes access to a sewage system but lacks piped water; no pesticide exposure is reported. She has both a personal and family history of skin cancer, which significantly elevates clinical concern. The lesion currently presents with itching and elevation, but information regarding growth and changes in appearance is unavailable. There are no reports of pain or bleeding. Given her personal and familial cancer history, lesion symptoms, and facial location, immediate dermatological evaluation is strongly recommended to clarify diagnosis and initiate appropriate treatment.",
    " The patient, identified as PAT_1693, is 45 years old and presents with a lesion on the chest. Specific details regarding lesion size, gender, Fitzpatrick skin type, family medical history, environmental exposures, and lifestyle habits are unavailable. The lesion currently exhibits itching as the sole symptom, with no reports of growth, pain, changes, bleeding, or elevation. Given the limited symptom profile and absence of additional clinical context, it is advisable to monitor the lesion closely and conduct a dermatological evaluation to rule out potential concerns.",
    " The patient, identified as PAT_302, is a 64-year-old male presenting with a lesion on the face measuring 10.0 x 10.0 mm. He has Fitzpatrick skin type 2 and a family background of German descent. His living conditions include access to piped water and a sewage system, with reported exposure to pesticides. Clinically, the patient has both a personal and family history of skin cancer. He is a smoker and does not consume alcohol. The lesion is symptomatic, showing itching, growth, pain, bleeding, and elevation—though no visible changes in appearance were noted. Considering the lesion’s facial location, size, and the patient’s oncological history and lifestyle risk factors, urgent dermatological evaluation and biopsy are recommended to rule out malignancy and guide timely treatment."
]


# Gerar os embeddings para todos os documentos
document_embeddings = embedding_model.encode(documents)

# Converter os embeddings para um formato que o FAISS pode usar (array numpy)
document_embeddings = np.array(document_embeddings).astype(np.float32)

# Criar o índice FAISS
index = faiss.IndexFlatL2(document_embeddings.shape[1])  # Usando o índice L2 (distância Euclidiana)
index.add(document_embeddings)  # Adicionando os embeddings ao índice

# Salvar o índice FAISS em um arquivo
faiss.write_index(index, "medical_index.faiss")

# Salvar os documentos em um arquivo pickle
with open("medical_documents.pkl", "wb") as f:
    pickle.dump(documents, f)

print("Índice FAISS e documentos salvos com sucesso!")