import faiss
import numpy as np
import pickle
from sentence_transformers import SentenceTransformer

# Modelo para embeddings
embedding_model = SentenceTransformer("Qwen/Qwen2.5-0.5B")

# Exemplo de documentos (pode carregar de um CSV, banco de dados, etc.)
documents = [
    "A 8-year-old patient (PAT_1516) with lesion ID 1765 located on the arm was recorded in the dataset. The lesion showed no symptoms such as itching, growth, pain, change, bleeding, or elevation. The patient’s family medical history, lifestyle factors (smoking, drinking), and exposure to pesticides were not provided. Additionally, there was no record of prior skin cancer history or general cancer history. An image of the lesion is available under PAT_1516_1765_530.png.",
    "A **55-year-old female patient** (PAT_46) with **lesion ID 881** located on the **neck** was recorded in the dataset. The lesion showed **symptoms such as itching, growth, changes, bleeding, and elevation, but no pain**. The patient has a **family background from Pomerania** and a **history of both skin cancer and general cancer**. She has **access to piped water and a sewage system** and has **not been exposed to pesticides**. An image of the lesion is available under **PAT_46_881_939.png**.",
    "A **77-year-old patient** (PAT_1545) with **lesion ID 1867** located on the **face** was recorded in the dataset. The lesion showed **itching but no growth, pain, changes, bleeding, or elevation**. The patient’s **family medical history, lifestyle factors (smoking, drinking), and exposure to pesticides** were not provided. Additionally, there was **no record of prior skin cancer history or general cancer history**. An image of the lesion is available under **PAT_1545_1867_547.png**.",
    "A **64-year-old male patient** (PAT_752) with **lesion ID 1426** located on the **neck** was recorded in the dataset. The lesion showed **itching, growth, bleeding, and elevation, but no pain or changes**. The patient has a **family background from the Netherlands and Italy** and a **history of skin cancer**. He has **access to piped water** but **no information about his exposure to pesticides or a sewage system**. An image of the lesion is available under **PAT_752_1426_714.png**.",
    "A **75-year-old patient** (PAT_1989) with **lesion ID 4061** located on the **hand** was recorded in the dataset. The lesion showed **itching but no growth, pain, changes, bleeding, or elevation**. The patient’s **family medical history, lifestyle factors (smoking, drinking), and exposure to pesticides** were not provided. Additionally, there was **no record of prior skin cancer history or general cancer history**. An image of the lesion is available under **PAT_1989_4061_934.png**.",
    "A **79-year-old male patient** (PAT_684) with **lesion ID 1302** located on the **forearm** was recorded in the dataset. The lesion showed **itching, growth, bleeding, and elevation, but no pain or changes**. The patient has a **family background from Pomerania**, a **history of skin cancer**, but no general cancer history. He **does not use pesticides**, has **access to piped water and a sewage system**, and has a **history of drinking but does not smoke**. An image of the lesion is available under **PAT_684_1302_588.png**.",
    "A **78-year-old female patient** (PAT_636) with **lesion ID 1204** located on the **chest** was recorded in the dataset. The lesion showed **itching, growth, pain, changes, bleeding, and elevation**. The patient has a **family background from Brazil** and a **history of both skin cancer and general cancer**. She has **access to piped water and a sewage system** and **has not been exposed to pesticides**. An image of the lesion is available under **PAT_636_1204_521.png**.",
    "A **56-year-old female patient** (PAT_614) with **lesion ID 1166** located on the **chest** was recorded in the dataset. The lesion showed **growth and changes, but no itching, pain, bleeding, or elevation**. The patient’s **family background is unknown**. She has a **history of general cancer but no reported history of skin cancer**. She has **access to piped water and a sewage system** and **has not been exposed to pesticides**. An image of the lesion is available under **PAT_614_1166_885.png**.",
    "A **54-year-old female patient** (PAT_359) with **lesion ID 4450** located on the **forearm** was recorded in the dataset. The lesion showed **no symptoms such as itching, growth, pain, changes, bleeding, or elevation**. The patient has a **family background from Italy** and a **history of both skin cancer and general cancer**. She has **access to piped water and a sewage system** and **has not been exposed to pesticides**. An image of the lesion is available under **PAT_359_4450_86.png**.",
    "A **52-year-old patient** (PAT_1306) with **lesion ID 1086** located on the **back** was recorded in the dataset. The lesion showed **no symptoms such as itching, growth, pain, changes, bleeding, or elevation**. The patient’s **family medical history, lifestyle factors (smoking, drinking), and exposure to pesticides** were not provided. Additionally, there was **no record of prior skin cancer history or general cancer history**. An image of the lesion is available under **PAT_1306_1086_762.png**.",
    "A **78-year-old female patient** (PAT_988) with **lesion ID 1858** located on the **face** was recorded in the dataset. The lesion showed **itching, growth, and elevation, but no pain, changes, bleeding**. The patient has a **family background from Pomerania** and a **history of skin cancer**, but **no record of general cancer history**. She has **access to piped water** but **no sewage system** and **has not been exposed to pesticides**. An image of the lesion is available under **PAT_988_1858_944.png**.",
    "A **69-year-old male patient** (PAT_115) with **lesion ID 177** located on the **forearm** was recorded in the dataset. The lesion showed **itching, growth, pain, bleeding, and elevation, but no changes**. The patient has a **family background from Pomerania** and a **history of skin cancer**, but **no record of general cancer history**. He has **access to piped water** and **a sewage system**, and has **not been exposed to pesticides**. An image of the lesion is available under **PAT_115_177_622.png**.",
    "An **81-year-old female patient** (PAT_338) with **lesion ID 710** located on the **thigh** was recorded in the dataset. The lesion showed **itching, growth, bleeding, and elevation, but no pain, changes**. The patient has a **family background from Germany** and a **history of skin cancer**, but **no record of general cancer history**. She has **access to piped water and a sewage system** and **has not been exposed to pesticides**. An image of the lesion is available under **PAT_338_710_93.png**.",
    "A **30-year-old male patient** (PAT_433) with **lesion ID 2650** located on the **neck** was recorded in the dataset. The lesion showed **growth and elevation, but no itching, pain, changes, bleeding**. The patient has a **family background from Germany** and **no history of skin cancer or general cancer**. He has **access to piped water** but **no sewage system** and **has not been exposed to pesticides**. An image of the lesion is available under **PAT_433_2650_417.png**.",
    "A **57-year-old female patient** (PAT_87) with **lesion ID 133** located on the **chest** was recorded in the dataset. The lesion showed **itching, growth, and elevation, but no pain, changes, bleeding**. The patient has a **family background from Pomerania** and **no history of skin cancer or general cancer**. She has **access to piped water** and **a sewage system**, but **has not been exposed to pesticides**. An image of the lesion is available under **PAT_87_133_159.png**.",
    "A **58-year-old patient** (PAT_2070) with **lesion ID 4430** located on the **arm** was recorded in the dataset. The lesion showed **no symptoms such as itching, growth, pain, changes, bleeding, or elevation**. The patient’s **family medical history, lifestyle factors (smoking, drinking), and exposure to pesticides** were not provided. Additionally, there was **no record of prior skin cancer history or general cancer history**. An image of the lesion is available under **PAT_2070_4430_290.png**.",
    "A **71-year-old male patient** (PAT_113) with **lesion ID 172** located on the **hand** was recorded in the dataset. The lesion showed **growth, bleeding, and elevation, but no itching, pain, changes**. The patient has a **family background from Germany** and a **history of skin cancer**, but **no record of general cancer history**. He has **access to piped water**, but **no information about exposure to pesticides or a sewage system**. An image of the lesion is available under **PAT_113_172_610.png**.",
    "A **47-year-old male patient** (PAT_97) with **lesion ID 151** located on the **chest** was recorded in the dataset. The lesion showed **itching, growth, and elevation, but no pain, changes, bleeding**. The patient has a **family background from Germany** and a **history of skin cancer**, but **no record of general cancer history**. He has **access to piped water** and **a sewage system**, and has **not been exposed to pesticides**. An image of the lesion is available under **PAT_97_151_587.png**.",
    "An **84-year-old male patient** (PAT_830) with **lesion ID 1564** located on the **nose** was recorded in the dataset. The lesion showed **itching, growth, and elevation, but no pain, changes, bleeding**. The patient has a **family background from Italy and Germany** and a **history of skin cancer**, but **no record of general cancer history**. He **smokes and drinks**, and has **access to piped water**, but **no information about exposure to pesticides or a sewage system**. An image of the lesion is available under **PAT_830_1564_740.png**."
    "A **68-year-old male patient** (PAT_360) with **lesion ID 742** located on the **forearm** was recorded in the dataset. The lesion showed **itching, growth, and elevation, but no pain, changes, bleeding**. The patient has a **family background from Italy** and a **history of skin cancer**, but **no record of general cancer history**. He has **access to piped water and a sewage system**, and has **not been exposed to pesticides**. The patient **smokes and drinks**. An image of the lesion is available under **PAT_360_742_768.png**.",
    "A **66-year-old male patient** (PAT_386) with **lesion ID 785** located on the **ear** was recorded in the dataset. The lesion showed **itching, growth, bleeding, and elevation, but no pain or changes**. The patient has a **family background from Pomerania** and a **history of skin cancer**, but **no record of general cancer history**. He has **access to piped water and a sewage system** and has **not been exposed to pesticides**. The patient **smokes** but **does not drink**. An image of the lesion is available under **PAT_386_785_536.png**.",
    "A **58-year-old female patient** (PAT_326) with **lesion ID 690** located on the **face** was recorded in the dataset. The lesion is **itching**, but shows **no changes, pain, or bleeding**. The patient has a **family background from Pomerania** and a **history of skin cancer**, but **no record of general cancer history**. She has **access to piped water and a sewage system**, and has **not been exposed to pesticides**. The patient **does not smoke or drink**. An image of the lesion is available under **PAT_326_690_823.png**.",
    "A **63-year-old female patient** (PAT_79) with **lesion ID 120** located on the **face** was recorded in the dataset. The lesion shows **no symptoms such as itching, growth, pain, changes, bleeding, or elevation**. The patient has a **family background from Pomerania** and **no history of skin cancer or general cancer**. She has **access to piped water and a sewage system**, and **has not been exposed to pesticides**. The patient **does not smoke or drink**. An image of the lesion is available under **PAT_79_120_532.png**.",
    "A **52-year-old patient** (PAT_1065) with **lesion ID 278** located on the **back** was recorded in the dataset. The lesion is **itching**, but shows **no changes, pain, bleeding, or elevation**. The patient's **family medical history and exposure to environmental factors** were not provided. There is **no record of prior skin cancer or general cancer history**. An image of the lesion is available under **PAT_1065_278_954.png**.",
    "An **82-year-old female patient** (PAT_107) with **lesion ID 160** located on the **chest** was recorded in the dataset. The lesion has **grown, elevated**, and has **diameters of 9.0 (diameter_1) and 8.0 (diameter_2)**. It also not shows **itching**, **no pain, changes, or bleeding**. The patient has a **family background from Pomerania** and **no history of skin cancer or general cancer**. She has **access to piped water**, but **no sewage system**, and has **not been exposed to pesticides**. The patient's **Fitzpatrick skin type is 1.0**, indicating very fair skin. The patient **does not smoke or drink**. An image of the lesion is available under **PAT_107_160_609.png**."
]


# Gerar os embeddings para todos os documentos
document_embeddings = embedding_model.encode(documents)

# Converter os embeddings para um formato que o FAISS pode usar (array numpy)
document_embeddings = np.array(document_embeddings).astype(np.float32)

# Criar o índice FAISS
index = faiss.IndexFlatL2(document_embeddings.shape[1])  # Usando o índice L2 (distância Euclidiana)
index.add(document_embeddings)  # Adicionando os embeddings ao índice

# Salvar o índice FAISS em um arquivo
faiss.write_index(index, "medical_index.faiss")

# Salvar os documentos em um arquivo pickle
with open("medical_documents.pkl", "wb") as f:
    pickle.dump(documents, f)

print("Índice FAISS e documentos salvos com sucesso!")